---
ci_cd:
  NAMESPACE: "{{ namespace_prefix }}-ci-cd"
  NAMESPACE_DISPLAY_NAME: "{{ namespace_prefix | title}}s CI/CD"

dev:
  NAMESPACE: "{{ namespace_prefix }}-dev"
  NAMESPACE_DISPLAY_NAME: " {{ namespace_prefix | title }}-dev"

test:
  NAMESPACE: "{{ namespace_prefix }}-test"
  NAMESPACE_DISPLAY_NAME: " {{ namespace_prefix | title }}-test"

ansible_connection: local
openshift_cluster_content:
- object: projectrequest
  content:
  - name: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/project-requests.yml"
    action: create
    params_from_vars: "{{ ci_cd }}" 
    tags:
    - projects
  - name: "{{ dev_namespace }}"
    template: "{{ playbook_dir }}/templates/project-requests.yml"
    action: create
    params_from_vars: "{{ dev }}" 
    tags:
    - projects
  - name: "{{ test_namespace }}"
    template: "{{ playbook_dir }}/templates/project-requests.yml"
    action: create
    params_from_vars: "{{ test }}" 
    tags:
    - projects
  
